### ISSUE TITLE
Godot AssetLib, fix two broken images

### ISSUE THREAD

**Issue by duianto** [imjp94/UIDesignTool#11]
Tested in:
v3.4.1.stable.official [aa1b95889]
Windows 10 21H1

This Godot plugin appeared when searching for "Tool", in the Godot AssetLib.

Clicking on the plugin, opened the info window: UI Design Tool

But it shows a broken image:

![broken image 1](https://user-images.githubusercontent.com/13420573/147211540-8f37b5c0-9cf9-48cc-a099-57f63c9429a7.png)

The second image works.

But scrolling the images to the right, shows another broken image:

![broken image 2](https://user-images.githubusercontent.com/13420573/147211636-4a6a6c3c-af98-416b-8a53-02db82ba8eb8.png)

**Comment by imjp94** [comment]
FYI, the links are not broken and they works fine in browser https://godotengine.org/asset-library/asset/717

The reason that both of the images are broken in Godot app is simply because gif files are not supported, and probably will never be supported https://github.com/godotengine/godot/pull/31831

Closing this issue as neither the links are broken or bug from engine
